services:
  - type: web
    name: ex-servicemen-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production